//! Deterministic per-key device fingerprint.
//!
//! The upstream treats a fingerprint as "the machine this account uses". It must
//! therefore be stable across restarts, redeploys and multi-instance runs, and
//! it must never report the host's real attributes. Every signal here is derived
//! from the API key instead of read from the machine.
//!
//! This is a byte-for-byte port of the original JavaScript implementation. The
//! golden fixtures in `fixtures/fingerprint_golden.json` were generated by
//! running that implementation, so any divergence fails the test suite. That
//! matters: a changed algorithm silently moves every account to a new device,
//! which is itself a suspicious signal.

#![forbid(unsafe_code)]

pub mod catalog;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::fingerprint::catalog::{CPUS, FP_SALT, MAC_COUNTS, MAIL_DOMAINS, MEMS_GIB, OS_USERS, TIMEZONES};

/// Attributes the upstream sees as the machine's real environment.
///
/// A single shared profile keeps the fingerprint, the request environment, the
/// working directory, the project slug and the lifecycle metadata from
/// contradicting each other, and keeps the host's own details off the wire.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeviceProfile {
    pub platform: String,
    pub arch: String,
    pub os_release: String,
    pub is_container: bool,
    /// Fake working directory; the project slug is derived from it.
    pub project_dir: String,
}

impl Default for DeviceProfile {
    fn default() -> Self {
        Self {
            platform: "win32".to_owned(),
            arch: "x64".to_owned(),
            os_release: "10.0.22631".to_owned(),
            is_container: false,
            project_dir: "C:\\Users\\dev\\projects\\app".to_owned(),
        }
    }
}

/// The derived identity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Fingerprint {
    pub thumbmark: String,
    pub components: FingerprintComponents,
}

/// Individual signals, as the upstream records them.
///
/// Each hash is absent when its source value is empty, matching the original
/// implementation's dropped `undefined` entries.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FingerprintComponents {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_id_hash: Option<String>,
    pub mac_hashes: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub os_user_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hostname_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub git_email_hash: Option<String>,
    pub platform: String,
    pub arch: String,
    pub os_release: String,
    pub cpu_model: String,
    pub cpu_count: u16,
    #[serde(rename = "memGiB")]
    pub mem_gib: u16,
    pub is_container: bool,
    pub timezone: String,
    pub runtime: String,
    pub collector_version: u8,
}

/// Derive the identity for `api_key`.
///
/// `salt` rotates the derived identity in bulk; the hashing salt stays fixed.
#[must_use]
pub fn generate_fingerprint(api_key: &str, salt: &str, profile: &DeviceProfile) -> Fingerprint {
    let (cpu_model, cpu_count) = CPUS[pick_index(salt, api_key, "cpu", CPUS.len(), |i| {
        format!("{}|{}", CPUS[i].0, CPUS[i].1)
    })];
    let mem_gib = MEMS_GIB[pick_index(salt, api_key, "mem", MEMS_GIB.len(), |i| MEMS_GIB[i].to_string())];
    let timezone = TIMEZONES[pick_index(salt, api_key, "timezone", TIMEZONES.len(), |i| TIMEZONES[i].to_owned())];
    let mac_count = MAC_COUNTS[pick_index(salt, api_key, "macCount", MAC_COUNTS.len(), |i| {
        MAC_COUNTS[i].to_string()
    })];
    let os_user = OS_USERS[pick_index(salt, api_key, "osUser", OS_USERS.len(), |i| OS_USERS[i].to_owned())];
    let mail_domain = MAIL_DOMAINS[pick_index(salt, api_key, "mailDomain", MAIL_DOMAINS.len(), |i| {
        MAIL_DOMAINS[i].to_owned()
    })];

    // Windows MachineGuid shape: 8-4-4-4-12.
    let machine_id_hex = hex_field(salt, api_key, "machineId", 16);
    let machine_id = format!(
        "{}-{}-{}-{}-{}",
        &machine_id_hex[0..8],
        &machine_id_hex[8..12],
        &machine_id_hex[12..16],
        &machine_id_hex[16..20],
        &machine_id_hex[20..32]
    );

    let mut macs: Vec<String> = (0..mac_count)
        .map(|index| {
            let bytes = digest(salt, api_key, &format!("mac{index}"));
            bytes[..6]
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<Vec<_>>()
                .join(":")
        })
        .collect();
    macs.sort();

    let hostname = format!("DESKTOP-{}", hex_field(salt, api_key, "hostname", 4).to_uppercase());
    let git_email = format!("{os_user}.{}@{mail_domain}", hex_field(salt, api_key, "gitEmail", 3));

    let thumbmark = thumbmark(&machine_id, &macs, &hostname, cpu_model);

    Fingerprint {
        thumbmark,
        components: FingerprintComponents {
            machine_id_hash: hash_signal(&machine_id),
            mac_hashes: macs.iter().filter_map(|mac| hash_signal(mac)).collect(),
            os_user_hash: hash_signal(os_user),
            hostname_hash: hash_signal(&hostname),
            git_email_hash: hash_signal(&git_email),
            platform: profile.platform.clone(),
            arch: profile.arch.clone(),
            os_release: profile.os_release.clone(),
            cpu_model: cpu_model.to_owned(),
            cpu_count,
            mem_gib,
            is_container: profile.is_container,
            timezone: timezone.to_owned(),
            runtime: "cli".to_owned(),
            collector_version: 1,
        },
    }
}

/// `sha256(salt + NUL + api_key + NUL + field)`.
fn digest(salt: &str, api_key: &str, field: &str) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(salt.as_bytes());
    hasher.update([0]);
    hasher.update(api_key.as_bytes());
    hasher.update([0]);
    hasher.update(field.as_bytes());
    hasher.finalize().into()
}

/// Deterministically choose one candidate for `field`.
///
/// Scores the candidates rather than taking a modulo: adding an entry later only
/// moves the keys whose new candidate actually wins, instead of reshuffling
/// every key at once.
fn pick_index(salt: &str, api_key: &str, field: &str, count: usize, label_of: impl Fn(usize) -> String) -> usize {
    let mut best_index = 0;
    let mut best_score: Option<[u8; 32]> = None;
    for index in 0..count {
        let score = digest(salt, api_key, &format!("{field}\0{}", label_of(index)));
        if best_score.is_none_or(|best| score > best) {
            best_score = Some(score);
            best_index = index;
        }
    }
    best_index
}

fn hex_field(salt: &str, api_key: &str, field: &str, bytes: usize) -> String {
    hex::encode(&digest(salt, api_key, field)[..bytes])
}

/// The CLI's `hashSignal`: fixed salt, lowercased value, empty means absent.
fn hash_signal(value: &str) -> Option<String> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return None;
    }
    let mut hasher = Sha256::new();
    hasher.update(FP_SALT.as_bytes());
    hasher.update([0]);
    hasher.update(trimmed.to_lowercase().as_bytes());
    Some(hex::encode(hasher.finalize()))
}

/// The CLI's `thumbmark`: the primary salt plus a machine-scoped seed.
///
/// The hostname and CPU model only contribute when there is no machine id, so a
/// machine that reports one does not get a second, redundant identity.
fn thumbmark(machine_id: &str, macs: &[String], hostname: &str, cpu_model: &str) -> String {
    let trimmed_machine_id = machine_id.trim();
    let mut seed_parts = vec![trimmed_machine_id.to_owned(), macs.join(",")];
    if trimmed_machine_id.is_empty() {
        seed_parts.push(hostname.to_owned());
        seed_parts.push(cpu_model.to_owned());
    }
    seed_parts.retain(|part| !part.is_empty());
    let joined = seed_parts.join("|");
    let seed = if joined.is_empty() { "unknown" } else { joined.as_str() };

    let mut hasher = Sha256::new();
    hasher.update(FP_SALT.as_bytes());
    hasher.update([0]);
    hasher.update(b"machine");
    hasher.update([0]);
    hasher.update(seed.as_bytes());
    hex::encode(hasher.finalize())
}
